language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install
script: 
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml test && php vendor/bin/coveralls -v

